name: Sync
on:
  schedule:
    # 13:33(UTC+8) Mon~Fri
    - cron: "33 5 * * 1-5"
  workflow_dispatch:
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Export variables
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          FUGLE_API_KEY: ${{ secrets.FUGLE_API_KEY }}
        run: |
          echo "NOTION_API_KEY=$NOTION_API_KEY" >> .env 
          echo "DATABASE_ID=$DATABASE_ID" >> .env
          echo "FUGLE_API_KEY=$FUGLE_API_KEY" >> .env
      - run: npm run execute
